
package stefanholzmueller.soapclient.sharepoint.lists;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListsSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListsSoap {


    /**
     * 
     * @param listName
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListResponse.GetListResult
     */
    @WebMethod(operationName = "GetList", action = "http://schemas.microsoft.com/sharepoint/soap/GetList")
    @WebResult(name = "GetListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListResponse.GetListResult getList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

    /**
     * 
     * @param listName
     * @param viewName
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListAndViewResponse.GetListAndViewResult
     */
    @WebMethod(operationName = "GetListAndView", action = "http://schemas.microsoft.com/sharepoint/soap/GetListAndView")
    @WebResult(name = "GetListAndViewResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListAndView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListAndView")
    @ResponseWrapper(localName = "GetListAndViewResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListAndViewResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListAndViewResponse.GetListAndViewResult getListAndView(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName);

    /**
     * 
     * @param listName
     */
    @WebMethod(operationName = "DeleteList", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteList")
    @RequestWrapper(localName = "DeleteList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteList")
    @ResponseWrapper(localName = "DeleteListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteListResponse")
    public void deleteList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

    /**
     * 
     * @param templateID
     * @param listName
     * @param description
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.AddListResponse.AddListResult
     */
    @WebMethod(operationName = "AddList", action = "http://schemas.microsoft.com/sharepoint/soap/AddList")
    @WebResult(name = "AddListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddList")
    @ResponseWrapper(localName = "AddListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddListResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.AddListResponse.AddListResult addList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String description,
        @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int templateID);

    /**
     * 
     * @param templateID
     * @param listName
     * @param description
     * @param featureID
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.AddListFromFeatureResponse.AddListFromFeatureResult
     */
    @WebMethod(operationName = "AddListFromFeature", action = "http://schemas.microsoft.com/sharepoint/soap/AddListFromFeature")
    @WebResult(name = "AddListFromFeatureResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddListFromFeature", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddListFromFeature")
    @ResponseWrapper(localName = "AddListFromFeatureResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddListFromFeatureResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.AddListFromFeatureResponse.AddListFromFeatureResult addListFromFeature(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String description,
        @WebParam(name = "featureID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String featureID,
        @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int templateID);

    /**
     * 
     * @param listName
     * @param deleteFields
     * @param listProperties
     * @param updateFields
     * @param listVersion
     * @param newFields
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.UpdateListResponse.UpdateListResult
     */
    @WebMethod(operationName = "UpdateList", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateList")
    @WebResult(name = "UpdateListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateList")
    @ResponseWrapper(localName = "UpdateListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateListResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.UpdateListResponse.UpdateListResult updateList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateList.ListProperties listProperties,
        @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateList.NewFields newFields,
        @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateList.UpdateFields updateFields,
        @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateList.DeleteFields deleteFields,
        @WebParam(name = "listVersion", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listVersion);

    /**
     * 
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListCollectionResponse.GetListCollectionResult
     */
    @WebMethod(operationName = "GetListCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetListCollection")
    @WebResult(name = "GetListCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListCollection")
    @ResponseWrapper(localName = "GetListCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListCollectionResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListCollectionResponse.GetListCollectionResult getListCollection();

    /**
     * 
     * @param listName
     * @param viewName
     * @param queryOptions
     * @param webID
     * @param query
     * @param viewFields
     * @param rowLimit
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListItemsResponse.GetListItemsResult
     */
    @WebMethod(operationName = "GetListItems", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItems")
    @WebResult(name = "GetListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListItems")
    @ResponseWrapper(localName = "GetListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListItemsResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListItemsResponse.GetListItemsResult getListItems(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName,
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItems.Query query,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItems.ViewFields viewFields,
        @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String rowLimit,
        @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItems.QueryOptions queryOptions,
        @WebParam(name = "webID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webID);

    /**
     * 
     * @param listName
     * @param viewFields
     * @param contains
     * @param since
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesResponse.GetListItemChangesResult
     */
    @WebMethod(operationName = "GetListItemChanges", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChanges")
    @WebResult(name = "GetListItemChangesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItemChanges", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListItemChanges")
    @ResponseWrapper(localName = "GetListItemChangesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesResponse.GetListItemChangesResult getListItemChanges(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItemChanges.ViewFields viewFields,
        @WebParam(name = "since", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String since,
        @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItemChanges.Contains contains);

    /**
     * 
     * @param listName
     * @param viewName
     * @param queryOptions
     * @param changeToken
     * @param query
     * @param viewFields
     * @param contains
     * @param rowLimit
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceTokenResponse.GetListItemChangesSinceTokenResult
     */
    @WebMethod(operationName = "GetListItemChangesSinceToken", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChangesSinceToken")
    @WebResult(name = "GetListItemChangesSinceTokenResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItemChangesSinceToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceToken")
    @ResponseWrapper(localName = "GetListItemChangesSinceTokenResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceTokenResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceTokenResponse.GetListItemChangesSinceTokenResult getListItemChangesSinceToken(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName,
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceToken.Query query,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceToken.ViewFields viewFields,
        @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String rowLimit,
        @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceToken.QueryOptions queryOptions,
        @WebParam(name = "changeToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String changeToken,
        @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.GetListItemChangesSinceToken.Contains contains);

    /**
     * 
     * @param listName
     * @param updates
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.UpdateListItemsResponse.UpdateListItemsResult
     */
    @WebMethod(operationName = "UpdateListItems", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateListItems")
    @WebResult(name = "UpdateListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateListItems")
    @ResponseWrapper(localName = "UpdateListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateListItemsResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.UpdateListItemsResponse.UpdateListItemsResult updateListItems(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "updates", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateListItems.Updates updates);

    /**
     * 
     * @param message
     * @param listName
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.AddDiscussionBoardItemResponse.AddDiscussionBoardItemResult
     */
    @WebMethod(operationName = "AddDiscussionBoardItem", action = "http://schemas.microsoft.com/sharepoint/soap/AddDiscussionBoardItem")
    @WebResult(name = "AddDiscussionBoardItemResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddDiscussionBoardItem", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddDiscussionBoardItem")
    @ResponseWrapper(localName = "AddDiscussionBoardItemResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddDiscussionBoardItemResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.AddDiscussionBoardItemResponse.AddDiscussionBoardItemResult addDiscussionBoardItem(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "message", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        byte[] message);

    /**
     * 
     * @param strFieldName
     * @param strlistItemID
     * @param strlistID
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetVersionCollectionResponse.GetVersionCollectionResult
     */
    @WebMethod(operationName = "GetVersionCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetVersionCollection")
    @WebResult(name = "GetVersionCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetVersionCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetVersionCollection")
    @ResponseWrapper(localName = "GetVersionCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetVersionCollectionResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetVersionCollectionResponse.GetVersionCollectionResult getVersionCollection(
        @WebParam(name = "strlistID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strlistID,
        @WebParam(name = "strlistItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strlistItemID,
        @WebParam(name = "strFieldName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strFieldName);

    /**
     * 
     * @param listName
     * @param listItemID
     * @param fileName
     * @param attachment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/AddAttachment")
    @WebResult(name = "AddAttachmentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddAttachment")
    @ResponseWrapper(localName = "AddAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.AddAttachmentResponse")
    public String addAttachment(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID,
        @WebParam(name = "fileName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String fileName,
        @WebParam(name = "attachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        byte[] attachment);

    /**
     * 
     * @param listName
     * @param listItemID
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetAttachmentCollectionResponse.GetAttachmentCollectionResult
     */
    @WebMethod(operationName = "GetAttachmentCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetAttachmentCollection")
    @WebResult(name = "GetAttachmentCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetAttachmentCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetAttachmentCollection")
    @ResponseWrapper(localName = "GetAttachmentCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetAttachmentCollectionResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetAttachmentCollectionResponse.GetAttachmentCollectionResult getAttachmentCollection(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID);

    /**
     * 
     * @param listName
     * @param listItemID
     * @param url
     */
    @WebMethod(operationName = "DeleteAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteAttachment")
    @RequestWrapper(localName = "DeleteAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteAttachment")
    @ResponseWrapper(localName = "DeleteAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteAttachmentResponse")
    public void deleteAttachment(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID,
        @WebParam(name = "url", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String url);

    /**
     * 
     * @param pageUrl
     * @param lastmodified
     * @param checkoutToLocal
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckOutFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckOutFile")
    @WebResult(name = "CheckOutFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CheckOutFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.CheckOutFile")
    @ResponseWrapper(localName = "CheckOutFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.CheckOutFileResponse")
    public boolean checkOutFile(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl,
        @WebParam(name = "checkoutToLocal", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String checkoutToLocal,
        @WebParam(name = "lastmodified", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String lastmodified);

    /**
     * 
     * @param pageUrl
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UndoCheckOut", action = "http://schemas.microsoft.com/sharepoint/soap/UndoCheckOut")
    @WebResult(name = "UndoCheckOutResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UndoCheckOut", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UndoCheckOut")
    @ResponseWrapper(localName = "UndoCheckOutResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UndoCheckOutResponse")
    public boolean undoCheckOut(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl);

    /**
     * 
     * @param checkinType
     * @param pageUrl
     * @param comment
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckInFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckInFile")
    @WebResult(name = "CheckInFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CheckInFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.CheckInFile")
    @ResponseWrapper(localName = "CheckInFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.CheckInFileResponse")
    public boolean checkInFile(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl,
        @WebParam(name = "comment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String comment,
        @WebParam(name = "CheckinType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String checkinType);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListContentTypesResponse.GetListContentTypesResult
     */
    @WebMethod(operationName = "GetListContentTypes", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentTypes")
    @WebResult(name = "GetListContentTypesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListContentTypes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListContentTypes")
    @ResponseWrapper(localName = "GetListContentTypesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListContentTypesResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListContentTypesResponse.GetListContentTypesResult getListContentTypes(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.GetListContentTypeResponse.GetListContentTypeResult
     */
    @WebMethod(operationName = "GetListContentType", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentType")
    @WebResult(name = "GetListContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListContentType")
    @ResponseWrapper(localName = "GetListContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.GetListContentTypeResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.GetListContentTypeResponse.GetListContentTypeResult getListContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param listName
     * @param contentTypeProperties
     * @param addToView
     * @param displayName
     * @param parentType
     * @param fields
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/CreateContentType")
    @WebResult(name = "CreateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CreateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.CreateContentType")
    @ResponseWrapper(localName = "CreateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.CreateContentTypeResponse")
    public String createContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "displayName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String displayName,
        @WebParam(name = "parentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String parentType,
        @WebParam(name = "fields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.CreateContentType.Fields fields,
        @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.CreateContentType.ContentTypeProperties contentTypeProperties,
        @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String addToView);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @param contentTypeProperties
     * @param deleteFields
     * @param updateFields
     * @param addToView
     * @param newFields
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeResponse.UpdateContentTypeResult
     */
    @WebMethod(operationName = "UpdateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentType")
    @WebResult(name = "UpdateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateContentType")
    @ResponseWrapper(localName = "UpdateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeResponse.UpdateContentTypeResult updateContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateContentType.ContentTypeProperties contentTypeProperties,
        @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateContentType.NewFields newFields,
        @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateContentType.UpdateFields updateFields,
        @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateContentType.DeleteFields deleteFields,
        @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String addToView);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.DeleteContentTypeResponse.DeleteContentTypeResult
     */
    @WebMethod(operationName = "DeleteContentType", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentType")
    @WebResult(name = "DeleteContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "DeleteContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteContentType")
    @ResponseWrapper(localName = "DeleteContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteContentTypeResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.DeleteContentTypeResponse.DeleteContentTypeResult deleteContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param newDocument
     * @param listName
     * @param contentTypeId
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeXmlDocumentResponse.UpdateContentTypeXmlDocumentResult
     */
    @WebMethod(operationName = "UpdateContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypeXmlDocument")
    @WebResult(name = "UpdateContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeXmlDocumentResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeXmlDocumentResponse.UpdateContentTypeXmlDocumentResult updateContentTypeXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypeXmlDocument.NewDocument newDocument);

    /**
     * 
     * @param newDocument
     * @param listName
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypesXmlDocumentResponse.UpdateContentTypesXmlDocumentResult
     */
    @WebMethod(operationName = "UpdateContentTypesXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypesXmlDocument")
    @WebResult(name = "UpdateContentTypesXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentTypesXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypesXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypesXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypesXmlDocumentResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypesXmlDocumentResponse.UpdateContentTypesXmlDocumentResult updateContentTypesXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        stefanholzmueller.soapclient.sharepoint.lists.UpdateContentTypesXmlDocument.NewDocument newDocument);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @param documentUri
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.DeleteContentTypeXmlDocumentResponse.DeleteContentTypeXmlDocumentResult
     */
    @WebMethod(operationName = "DeleteContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentTypeXmlDocument")
    @WebResult(name = "DeleteContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "DeleteContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteContentTypeXmlDocument")
    @ResponseWrapper(localName = "DeleteContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.DeleteContentTypeXmlDocumentResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.DeleteContentTypeXmlDocumentResponse.DeleteContentTypeXmlDocumentResult deleteContentTypeXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "documentUri", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String documentUri);

    /**
     * 
     * @param webUrl
     * @param listName
     * @param contentTypeId
     * @return
     *     returns stefanholzmueller.soapclient.sharepoint.lists.ApplyContentTypeToListResponse.ApplyContentTypeToListResult
     */
    @WebMethod(operationName = "ApplyContentTypeToList", action = "http://schemas.microsoft.com/sharepoint/soap/ApplyContentTypeToList")
    @WebResult(name = "ApplyContentTypeToListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "ApplyContentTypeToList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.ApplyContentTypeToList")
    @ResponseWrapper(localName = "ApplyContentTypeToListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "stefanholzmueller.soapclient.sharepoint.lists.ApplyContentTypeToListResponse")
    public stefanholzmueller.soapclient.sharepoint.lists.ApplyContentTypeToListResponse.ApplyContentTypeToListResult applyContentTypeToList(
        @WebParam(name = "webUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webUrl,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

}
